components:
  examples:
    json_400_panui_mgmt_bad_xpath:
      summary: Bad XPath
      value:
        _errors:
        - code: E013
          details: {}
          message: Bad XPath
        _request_id: abcd-1234
    json_400_panui_mgmt_invalid_command:
      summary: Invalid Command
      value:
        _errors:
        - code: E003
          details: {}
          message: Invalid Command
        _request_id: abcd-1234
    json_400_panui_mgmt_invalid_object:
      summary: Invalid Object
      value:
        _errors:
        - code: E003
          details: {}
          message: Invalid Object
        _request_id: abcd-1234
    json_400_panui_mgmt_malformed_command:
      summary: Malformed Command
      value:
        _errors:
        - code: E003
          details: {}
          message: Malformed Command
        _request_id: abcd-1234
    json_400_panui_restapi_input_format_mismatch:
      summary: Input Format Mismatch
      value:
        _errors:
        - code: E003
          details: {}
          message: 'Input Format Mismatch: input-format=json'
        _request_id: abcd-1234
    json_400_panui_restapi_invalid_query_parameter:
      summary: Invalid Query Parameter
      value:
        _errors:
        - code: E003
          details: {}
          message: 'Invalid Query Parameter: location=invalid'
        _request_id: abcd-1234
    json_400_panui_restapi_missing_body:
      summary: Missing Body
      value:
        _errors:
        - code: E003
          details: {}
          message: Missing Body
        _request_id: abcd-1234
    json_400_panui_restapi_missing_query_parameter:
      summary: Missing Query Parameter
      value:
        _errors:
        - code: E003
          details: {}
          message: 'Missing Query Parameter: name'
        _request_id: abcd-1234
    json_400_panui_restapi_output_format_mismatch:
      summary: Output Format Mismatch
      value:
        _errors:
        - code: E003
          details: {}
          message: 'Output Format Mismatch: output-format=json Accept=xml'
        _request_id: abcd-1234
    json_401_panui_auth_invalid_credential:
      summary: Invalid Credential
      value:
        _errors:
        - code: E016
          details: {}
          message: Invalid Credential
        _request_id: abcd-1234
    json_401_panui_auth_key_expired:
      summary: Key Expired
      value:
        _errors:
        - code: E016
          details: {}
          message: Key Expired
        _request_id: abcd-1234
    json_401_panui_auth_key_too_long:
      summary: Key Too Long
      value:
        _errors:
        - code: E016
          details: {}
          message: Key Too Long
        _request_id: abcd-1234
    json_401_panui_auth_need_password_change:
      summary: Need Password Change
      value:
        _errors:
        - code: E016
          details: {}
          message: The password needs to be changed.
        _request_id: abcd-1234
    json_401_panui_auth_not_authenticated:
      summary: Not Authenticated
      value:
        _errors:
        - code: E016
          details: {}
          message: Not Authenticated
        _request_id: abcd-1234
    json_403_panui_auth_unauthorized:
      summary: Unauthorized
      value:
        _errors:
        - code: E007
          details: {}
          message: Unauthorized
        _request_id: abcd-1234
    json_404_panui_mgmt_object_not_present:
      summary: Object Not Present
      value:
        _errors:
        - code: E005
          details: {}
          message: Object Not Present
        _request_id: abcd-1234
    json_405_panui_restapi_action_not_supported:
      summary: Action Not Supported
      value:
        _errors:
        - code: E012
          details: {}
          message: 'Action Not Supported: move'
        _request_id: abcd-1234
    json_409_panui_mgmt_name_not_unique:
      summary: Name Not Unique
      value:
        _errors:
        - code: E006
          details: {}
          message: Name Not Unique
        _request_id: abcd-1234
    json_409_panui_mgmt_object_not_unique:
      summary: Object Not Unique
      value:
        _errors:
        - code: E016
          details: {}
          message: Object Not Unique
        _request_id: abcd-1234
    json_409_panui_mgmt_reference_not_zero:
      summary: Reference Not Zero
      value:
        _errors:
        - code: E009
          details: {}
          message: Reference Not Zero
        _request_id: abcd-1234
    json_501_panui_restapi_method_not_supported:
      summary: Method Not Supported
      value:
        _errors:
        - code: E012
          details: {}
          message: Method Not Supported
        _request_id: abcd-1234
    json_501_panui_restapi_version_not_supported:
      summary: Version Not Supported
      value:
        _errors:
        - code: E012
          details: {}
          message: Version Not Supported
        _request_id: abcd-1234
    json_504_panui_mgmt_session_timeout:
      summary: Session Timeout
      value:
        _errors:
        - code: 4
          details: {}
          message: Session Timeout
        _request_id: abcd-1234
  parameters:
    name-optional:
      description: The name of the entry
      in: query
      name: name
      required: false
      schema:
        type: string
    scope:
      description: "Specifies the scope of the operation. If creating\nan object,\
        \ the object is created only within the\nspecified scope. If retrieving objects,\
        \ the \nobjects are retrieved only from within the specified scope.\n\n`shared`\
        \ indicates that the scope is your entire Prisma Access instance. \n"
      in: query
      name: scope
      required: true
      schema:
        enum:
        - Shared
        - Mobile Users
        - Remote Networks
        - Service Connections
        - Mobile Users Container
        - Mobile Users Explicit Proxy
        type: string
    uuid-required:
      description: The uuid of the resource
      in: path
      name: uuid
      required: true
      schema:
        type: string
  responses:
    access_errors:
      content:
        application/json:
          examples:
            auth_unauthorized:
              $ref: '#/components/examples/json_403_panui_auth_unauthorized'
          schema:
            $ref: '#/components/schemas/generic_error'
      description: Forbidden
    auth_errors:
      content:
        application/json:
          examples:
            auth_not_authenticated:
              $ref: '#/components/examples/json_401_panui_auth_not_authenticated'
            invalid_credential:
              $ref: '#/components/examples/json_401_panui_auth_invalid_credential'
            key_expired:
              $ref: '#/components/examples/json_401_panui_auth_key_expired'
            key_too_long:
              $ref: '#/components/examples/json_401_panui_auth_key_too_long'
            need_password_change:
              $ref: '#/components/examples/json_401_panui_auth_need_password_change'
          schema:
            $ref: '#/components/schemas/generic_error'
      description: Unauthorized
    bad_request_errors_basic:
      content:
        application/json:
          examples:
            input_format_mismatch:
              $ref: '#/components/examples/json_400_panui_restapi_input_format_mismatch'
            invalid_query_parameter:
              $ref: '#/components/examples/json_400_panui_restapi_invalid_query_parameter'
            missing_query_parameter:
              $ref: '#/components/examples/json_400_panui_restapi_missing_query_parameter'
            output_format_mismatch:
              $ref: '#/components/examples/json_400_panui_restapi_output_format_mismatch'
          schema:
            $ref: '#/components/schemas/generic_error'
      description: Bad Request
    bad_request_errors_basic_with_body:
      content:
        application/json:
          examples:
            input_format_mismatch:
              $ref: '#/components/examples/json_400_panui_restapi_input_format_mismatch'
            invalid_object:
              $ref: '#/components/examples/json_400_panui_mgmt_invalid_object'
            invalid_query_parameter:
              $ref: '#/components/examples/json_400_panui_restapi_invalid_query_parameter'
            missing_body:
              $ref: '#/components/examples/json_400_panui_restapi_missing_body'
            missing_query_parameter:
              $ref: '#/components/examples/json_400_panui_restapi_missing_query_parameter'
            output_format_mismatch:
              $ref: '#/components/examples/json_400_panui_restapi_output_format_mismatch'
          schema:
            $ref: '#/components/schemas/generic_error'
      description: Bad Request
    conflict_errors:
      content:
        application/json:
          examples:
            name_not_unique:
              $ref: '#/components/examples/json_409_panui_mgmt_name_not_unique'
            object_not_unique:
              $ref: '#/components/examples/json_409_panui_mgmt_object_not_unique'
            reference_not_zero:
              $ref: '#/components/examples/json_409_panui_mgmt_reference_not_zero'
          schema:
            $ref: '#/components/schemas/generic_error'
      description: Conflict
    default_errors:
      content:
        application/json:
          examples:
            action_not_supported:
              $ref: '#/components/examples/json_405_panui_restapi_action_not_supported'
            bad_xpath:
              $ref: '#/components/examples/json_400_panui_mgmt_bad_xpath'
            invalid_command:
              $ref: '#/components/examples/json_400_panui_mgmt_invalid_command'
            malformed_command:
              $ref: '#/components/examples/json_400_panui_mgmt_malformed_command'
            method_not_allowed:
              $ref: '#/components/examples/json_501_panui_restapi_method_not_supported'
            session_timeout:
              $ref: '#/components/examples/json_504_panui_mgmt_session_timeout'
            version_not_supported:
              $ref: '#/components/examples/json_501_panui_restapi_version_not_supported'
          schema:
            $ref: '#/components/schemas/generic_error'
      description: General Errors
    http_created:
      description: Created
    http_ok:
      description: Ok
    not_found:
      content:
        application/json:
          examples:
            object_not_present:
              $ref: '#/components/examples/json_404_panui_mgmt_object_not_present'
          schema:
            $ref: '#/components/schemas/generic_error'
      description: Not Found
  schemas:
    error_detail_cause_info:
      properties:
        code:
          type: string
        details:
          type: object
        help:
          type: string
        message:
          type: string
      title: Cause Info
      type: object
    error_detail_cause_infos:
      items:
        $ref: '#/components/schemas/error_detail_cause_info'
      type: array
    generic_error:
      properties:
        _errors:
          $ref: '#/components/schemas/error_detail_cause_infos'
        _request_id:
          type: string
      type: object
    objects-address-groups:
      oneOf:
      - properties:
          static:
            items:
              maxLength: 63
              type: string
              x-panMemberOf:
              - location: shared
                schema: address-group
                subPath: name
            type: array
        required:
        - static
        title: static
      - properties:
          dynamic:
            properties:
              filter:
                description: Tag based filter defining group membership e.g. `tag1
                  AND tag2 OR tag3`
                maxLength: 2047
                type: string
            required:
            - filter
            type: object
        required:
        - dynamic
        title: dynamic
      properties:
        description:
          maxLength: 1023
          minLength: 0
          type: string
        name:
          description: Alphanumeric string [ 0-9a-zA-Z._-]
          maxLength: 63
          type: string
        tag:
          description: Tags for address group object
          items:
            maxLength: 127
            type: string
          maxItems: 64
          type: array
      required:
      - name
      type: object
info:
  contact: {}
  description: 'Manages address groups that simplify the creation of policy rules.

    '
  title: Address Group Management
  version: beta
  x-logo:
    url: pan-logo.png
openapi: 3.0.0
paths:
  /config/v1/address-groups:
    delete:
      description: 'Delete an address group.

        '
      operationId: delete-config-v1-address-groups
      parameters:
      - $ref: '#/components/parameters/uuid-required'
      responses:
        '200':
          $ref: '#/components/responses/http_ok'
        '400':
          $ref: '#/components/responses/bad_request_errors_basic'
        '401':
          $ref: '#/components/responses/auth_errors'
        '403':
          $ref: '#/components/responses/access_errors'
        '404':
          $ref: '#/components/responses/not_found'
        '409':
          $ref: '#/components/responses/conflict_errors'
        default:
          $ref: '#/components/responses/default_errors'
      summary: Delete an address group
      tags:
      - AddressGroups
    get:
      description: 'Get address groups.

        '
      operationId: get-config-v1-address-groups
      parameters:
      - $ref: '#/components/parameters/name-optional'
      - $ref: '#/components/parameters/scope'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                - items:
                    $ref: '#/components/schemas/objects-address-groups'
                  type: array
          description: List of address groups
        '400':
          $ref: '#/components/responses/bad_request_errors_basic'
        '401':
          $ref: '#/components/responses/auth_errors'
        '403':
          $ref: '#/components/responses/access_errors'
        '404':
          $ref: '#/components/responses/not_found'
        default:
          $ref: '#/components/responses/default_errors'
      summary: List address groups
      tags:
      - AddressGroups
    post:
      description: 'Create an address group.

        '
      operationId: post-config-v1-address-groups
      parameters:
      - $ref: '#/components/parameters/scope'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/objects-address-groups'
        description: The address group you want to create
      responses:
        '201':
          $ref: '#/components/responses/http_created'
        '400':
          $ref: '#/components/responses/bad_request_errors_basic_with_body'
        '401':
          $ref: '#/components/responses/auth_errors'
        '403':
          $ref: '#/components/responses/access_errors'
        '409':
          $ref: '#/components/responses/conflict_errors'
        default:
          $ref: '#/components/responses/default_errors'
      summary: Create an address group
      tags:
      - AddressGroups
    put:
      description: 'Modify an address group.

        '
      operationId: put-config-v1-address-groups
      parameters:
      - $ref: '#/components/parameters/uuid-required'
      - $ref: '#/components/parameters/scope'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/objects-address-groups'
        description: The address group you want to edit
      responses:
        '200':
          $ref: '#/components/responses/http_ok'
        '400':
          $ref: '#/components/responses/bad_request_errors_basic_with_body'
        '401':
          $ref: '#/components/responses/auth_errors'
        '403':
          $ref: '#/components/responses/access_errors'
        '404':
          $ref: '#/components/responses/not_found'
        '409':
          $ref: '#/components/responses/conflict_errors'
        default:
          $ref: '#/components/responses/default_errors'
      summary: Edit an address group
      tags:
      - AddressGroups
tags:
- name: AddressGroups
